name: Measure 📈
description: Metrics and analytics tracking
title: '|'
type: 'Measure 📈'
projects: ['StaytunedLLP/42', 'StaytunedLLP/72']

body:
  - type: markdown
    attributes:
      value: |
        🚀 Speed Leads, Ship Every Day.

  - type: textarea
    attributes:
      label: Description
      value: |
        As a
        I want to
        so that

        ### Why this is important

        1. 

        ### Details

        1. [File Name](Link) - Brief description of the file

        ### Diagrams

        1. [File/Diagram Name](Link) - Brief description of the diagram

        ### Designs

        1. [File/Design Name](Link) - Brief description of the design

        ### Association

        Feature #00
        Story #00

        ### Acceptance Criteria

        - [ ] 

        ### Additional Context
