name: Data 💾
description: Information or dataset change
type: 'Data 💾'
projects: []

body:
  - type: markdown
    attributes:
      value: Let AI build, be orchestrator, ship instantly. 🤖🪄🚀
      
  - type: textarea
    attributes:
      label: Description
      value: |
        ### Objective

        1. 

        ### Notes

        1. 

        ### Relations

        - Issue or link