name: Feature 🧩
description: A request, idea or new functionality
type: 'Feature 🧩'
projects: ["StaytunedLLP/43"]

body:
  - type: markdown
    attributes:
      value: Let AI build, be orchestrator, ship instantly. 🤖🪄🚀
      
  - type: textarea
    attributes:
      label: Description
      value: |