name: Flag 🚩
description: Feature flag or toggle
type: 'Flag 🚩'
projects: ["StaytunedLLP/43"]

body:
  - type: markdown
    attributes:
      value: Let AI build, be orchestrator, ship instantly. 🤖🪄🚀

  - type: textarea
    attributes:
      label: Description
      value: |
        ### Flag Objective

        1.   

        ### Configuration

        1. Flag key:
        2. Flag type:
        3. Default value:

        ### Rollout plan

        - Target audience:
        - Phased rollout (percentage / cohorts):
        - Start date:
        - Evaluation date:

        ### Targeting / Criteria

        - Conditions for enabling (user segment, environment, region, etc.)

        ### Success Metrics

        1. Metric name - measurement method & target

        ### Monitoring & Alerting

        - Metrics/logs to monitor
        - Alerting thresholds and recipients

        ### Rollback

        - Conditions that trigger rollback
        - Steps to disable the flag immediately

        ### Dependencies & Migration

        - Services/components affected
        - Any required data/schema migrations

        ### Cleanup Plan

        - Criteria for flag removal
        - Estimated removal date

        ### Acceptance Criteria

        - [ ] Solve with observations that enable 100× faster future repetitions.
        - [ ] 
        - [ ] Flag created with correct key and default state
        - [ ] Targeting rules implemented and tested
        - [ ] Metrics and monitoring in place
        - [ ] Rollback procedure documented and validated
        - [ ] Process updated and remaining speed gaps logged as issues. (#issues)

        ### context