name: Instruction 🤖
description: Instruction for AI-driven process
type: 'Instruction 🤖'
projects: ["StaytunedLLP/43"]

body:
  - type: markdown
    attributes:
      value: Let AI build, be orchestrator, ship instantly. 🤖🪄🚀

  - type: textarea
    attributes:
      label: Description
      value: |
        ### Objective
        
        1. 

        ### Usage Scenario

        1. 

        ### Context

        1. 

        ### Instruction (v1)

        [File OR Folder Path]

        OR as following:

        ```text
        [Insert instruction text here]
        ```