name: Publish 📢
description: Marketing workflow tracking
type: 'Publish 📢'
projects: ["StaytunedLLP/54"]

body:
  - type: markdown
    attributes:
      value: Let AI build, be orchestrator, ship instantly. 🤖🪄🚀

  - type: textarea
    attributes:
      label: Description
      value: |
        ### Objective
        
        1. 

        ### Channel & Timing

        1. Format:
        2. Platform:
        3. Go-Live Date & Time: 

        ### Assets

        1. Content:
        2. Creative/Thumbnail:

        ### Acceptance Criteria

        - [ ] Solve with observations that enable 100× faster future repetitions.
        - [ ] Content finalized
        - [ ] Creative/Thumbnail finalized
        - [ ] Proofread & Approved
        - [ ] SEO / Alt-text check
        - [ ] Links tested (No 404s)
        - [ ] Scheduled for publishing
        - [ ] 
        - [ ] Process updated and remaining speed gaps logged as issues. (#issues)

        ### Context
