name: Task 📀
description: Single, trackable work activity
type: "Task 📀"
projects: ["StaytunedLLP/43"]

body:
  - type: markdown
    attributes:
      value: Let AI build, be orchestrator, ship instantly. 🤖🪄🚀

  - type: textarea
    attributes:
      label: Description
      value: |
        ### Objective

        1. 

        ### Acceptance Criteria

        - [ ] Solve with observations that enable 100× faster future repetitions.
        - [ ] 
        - [ ] Process updated and remaining speed gaps logged as issues. (#issues) 

        ### Context
