name: Workflow 🔄
description: Process or sequence of tasks
type: 'Workflow 🔄'
projects: ["StaytunedLLP/43"]

body:
  - type: markdown
    attributes:
      value: Let AI build, be orchestrator, ship instantly. 🤖🪄🚀

  - type: textarea
    attributes:
      label: Description
      value: |
        ### Objective

        1. 

        ### Trigger

        1. Type: [e.g. Scheduled (Cron) / Webhook / Manual Trigger]
        2. Event: [e.g. "Every Monday at 09:00 UTC" OR "On PR Merge to Main"]

        ### Steps

        1. Fetch:
        2. Process:
        3. Store:

        ### Outcome

        1. [e.g. Artifact generated, Notification sent]

        ### Failure Handling

        1. If it fails: [e.g. Retry, Alert Team]
        2. Alerts: Notify team

        Feature #00
        Story #00

        ### Acceptance Criteria

        - [ ] Solve with observations that enable 100× faster future repetitions.
        - [ ] 
        - [ ] Process updated and remaining speed gaps logged as issues. (#issues)

        ### Context